// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiQz5WJD8--ZU20mEseVFiZvE6Cv-qZIY',
    appId: '1:858823327301:web:26b91f3e66164cb9022d2c',
    messagingSenderId: '858823327301',
    projectId: 'yogya-app',
    authDomain: 'yogya-app.firebaseapp.com',
    storageBucket: 'yogya-app.firebasestorage.app',
    measurementId: 'G-VGRFC80KGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZrxcwoWVK5QSrOosZWeVEbRtAmPdMiY',
    appId: '1:858823327301:android:2777ac3c541c5035022d2c',
    messagingSenderId: '858823327301',
    projectId: 'yogya-app',
    storageBucket: 'yogya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvdk20QXxCeP2sELNb2PsEB6rzu6MeRQo',
    appId: '1:858823327301:ios:007a7f3ef97db4bc022d2c',
    messagingSenderId: '858823327301',
    projectId: 'yogya-app',
    storageBucket: 'yogya-app.firebasestorage.app',
    iosClientId: '858823327301-nd2k0gntrf9fssg3su227eudts5tqmpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogyaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvdk20QXxCeP2sELNb2PsEB6rzu6MeRQo',
    appId: '1:858823327301:ios:007a7f3ef97db4bc022d2c',
    messagingSenderId: '858823327301',
    projectId: 'yogya-app',
    storageBucket: 'yogya-app.firebasestorage.app',
    iosClientId: '858823327301-nd2k0gntrf9fssg3su227eudts5tqmpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.yogyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiQz5WJD8--ZU20mEseVFiZvE6Cv-qZIY',
    appId: '1:858823327301:web:431b8eb3a7706d6f022d2c',
    messagingSenderId: '858823327301',
    projectId: 'yogya-app',
    authDomain: 'yogya-app.firebaseapp.com',
    storageBucket: 'yogya-app.firebasestorage.app',
    measurementId: 'G-WNL0HDGF94',
  );
}
